### ISSUE TITLE
Patch for sfence.vma

### ISSUE THREAD

**Issue by Yuan-Mao** [black-parrot-sdk/bp-linux#5]
@dpetrisko
Hi Dan, do we still need this change for sfence.vma (https://github.com/black-parrot-sdk/bp-linux/blob/master/cfg/linux.patch)?
~I just ran without this on Dromajo and it seems fine to me.~ -> Actually I was running with that patch. 
Thanks!

**Comment by dpetrisko** [comment]
Should not need that patch anymore

**Comment by muwyse** [comment]
This was resolved in a PR at some point. Closing.
